import { evaluate, evaluateExact, factorial, constants, normalizeAngleMode } from './packages/calculator-core/index.js';

(() => {
  const $ = id => document.getElementById(id);
  const primary = () => $('displayPrimary');
  const secondary = () => $('displaySecondary');
  const preview = () => $('expressionPreview');
  const historyList = () => $('historyList');
  const historyCount = () => $('historyCount');
  let expression = '';
  let justCalculated = false;
  let angleMode = localStorage.getItem('calculatorAngleMode') || 'DEG';
  if (!['DEG', 'RAD', 'GRAD'].includes(angleMode)) angleMode = 'DEG';
  const operators = new Set(['+', '-', '*', '/', '%', '^']);
  const actionOperators = { add: '+', subtract: '-', multiply: '*', divide: '/' };
  const scientificActions = ['sin','cos','tan','asin','acos','atan','log','ln','sqrt','abs','floor','ceil','round','exp','square','reciprocal','percent','factorial','pi','e','tau','phi'];

  function format(value) { const n=Number(value); if(!Number.isFinite(n))return 'Error'; if(Math.abs(n)>=1e10||(Math.abs(n)<1e-8&&n!==0))return n.toExponential(8); return n.toLocaleString('en-US',{maximumFractionDigits:10,useGrouping:false}); }
  function display(text=expression||'0',sub=''){if(primary())primary().textContent=text;if(secondary())secondary().textContent=sub;const node=preview();if(node){node.textContent=expression;node.classList.toggle('active',Boolean(expression));}}
  function animate(target){if(typeof anime!=='function'||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;const node=typeof target==='string'?document.querySelector(target):target;if(!node)return;anime.remove(node);anime({targets:node,scale:[1,.985,1],duration:150,easing:'easeOutCubic'});}
  function readHistory(){try{const value=JSON.parse(localStorage.getItem('calculatorHistory')||'[]');return Array.isArray(value)?value.slice(0,50):[];}catch{return[];}}
  function saveHistory(items){try{localStorage.setItem('calculatorHistory',JSON.stringify(items.slice(0,50)));}catch{}}
  function addHistory(expr,result){const items=readHistory();items.unshift({expression:expr,result:String(result),time:Date.now()});saveHistory(items);renderHistory();}
  function renderHistory(){const list=historyList(),count=historyCount(),items=readHistory();if(count)count.textContent=String(items.length);if(!list)return;list.replaceChildren();if(!items.length){const empty=document.createElement('div');empty.className='history-empty';empty.textContent='No calculations yet';list.appendChild(empty);return;}for(const item of items){const button=document.createElement('button');button.type='button';button.className='history-item';const left=document.createElement('span'),right=document.createElement('span');left.className='history-expression';right.className='history-result';left.textContent=item.expression;right.textContent=`= ${format(item.result)}`;button.append(left,right);button.addEventListener('click',()=>{expression=String(item.result);justCalculated=true;display(format(item.result),'History recall');animate(primary());});list.appendChild(button);}}
  function clear(){expression='';justCalculated=false;display('0','');}
  function appendNumber(value){if(justCalculated)expression='';justCalculated=false;expression+=value;display(expression);}
  function appendDecimal(){if(justCalculated)expression='';justCalculated=false;const last=expression.at(-1);if(last===')')return;const tail=expression.split(/[+\-*/%^()]/).pop()||'';if(tail.includes('.'))return;expression+=tail?'.':'0.';display(expression);}
  function appendParenthesis(value){if(justCalculated)expression='';justCalculated=false;const last=expression.at(-1);if(value==='('){if(last&&/[0-9.)]/.test(last))expression+='*';expression+='(';}else{const opens=(expression.match(/\(/g)||[]).length,closes=(expression.match(/\)/g)||[]).length;if(opens<=closes||!last||operators.has(last)||last==='(')return;expression+=')';}display(expression);}
  function appendOperator(operator){if(!expression){if(operator==='-')expression='-';else return;}else if(operators.has(expression.at(-1)))expression=expression.slice(0,-1)+operator;else if(expression.at(-1)==='('&&operator!=='-')return;else expression+=operator;justCalculated=false;display(expression);}
  function calculate(){if(!expression)return;try{const result=evaluate(expression,{}, {angleMode});addHistory(expression,result);display(format(result),`${expression} =`);expression=String(result);justCalculated=true;animate(primary());}catch(error){display('Error',error?.message||'Invalid expression');setTimeout(()=>{if(primary()?.textContent==='Error')clear();},1800);}}
  function scientific(action){try{if(['pi','e','tau','phi'].includes(action)){if(expression&&!justCalculated)expression+='*';expression+=action;justCalculated=false;display(expression);return;}if(!expression)return;const value=evaluate(expression,{}, {angleMode});let result;if(action==='square')result=value**2;else if(action==='reciprocal'){if(value===0)throw new Error('Cannot divide by zero');result=1/value;}else if(action==='percent')result=value/100;else if(action==='factorial')result=factorial(value);else result=evaluate(`${action}(${expression})`,{}, {angleMode});if(!Number.isFinite(result))throw new Error('Result is not finite');const label=`${action}(${expression})`;addHistory(label,result);expression=String(result);justCalculated=true;display(format(result),label);animate(primary());}catch(error){display('Error',error?.message||'Invalid calculation');setTimeout(()=>{if(primary()?.textContent==='Error')clear();},1800);}}
  function toggleAngleMode(){angleMode={DEG:'RAD',RAD:'GRAD',GRAD:'DEG'}[angleMode];localStorage.setItem('calculatorAngleMode',angleMode);updateScientificUI();}
  function toggleExact(){if(!expression)return;try{const result=evaluateExact(expression);addHistory(`${expression} [exact]`,result.toString());expression=result.toString();justCalculated=true;display(result.toString(),'Exact result');animate(primary());}catch(error){display('Error',error?.message||'Exact mode unavailable');setTimeout(()=>{if(primary()?.textContent==='Error')clear();},1800);}}
  function createScientificUI(){const tools=document.querySelector('.calculator-tools');if(!tools||document.getElementById('phase2ScientificToggle'))return;const sci=document.createElement('button');sci.className='tool-button';sci.id='phase2ScientificToggle';sci.type='button';sci.setAttribute('aria-expanded','false');sci.innerHTML='<i class="fas fa-flask"></i> Scientific';const exact=document.createElement('button');exact.className='tool-button';exact.type='button';exact.id='phase2ExactToggle';exact.innerHTML='<i class="fas fa-divide"></i> Exact';tools.append(sci,exact);const panel=document.createElement('section');panel.className='history-panel phase2-scientific-panel';panel.id='phase2ScientificPanel';panel.hidden=true;panel.innerHTML='<div class="history-header"><span>Scientific Mode</span><button class="tool-button" id="phase2AngleToggle" type="button"></button></div><div class="phase2-scientific-grid"></div>';const grid=panel.querySelector('.phase2-scientific-grid');const labels={sin:'sin',cos:'cos',tan:'tan',asin:'asin',acos:'acos',atan:'atan',log:'log',ln:'ln',sqrt:'√',abs:'abs',floor:'floor',ceil:'ceil',round:'round',exp:'exp',square:'x²',reciprocal:'1/x',percent:'%',factorial:'x!',pi:'π',e:'e',tau:'τ',phi:'φ'};for(const action of scientificActions){const b=document.createElement('button');b.type='button';b.className='btn btn-function';b.dataset.action=action;b.textContent=labels[action];grid.appendChild(b);}tools.after(panel);sci.addEventListener('click',()=>{panel.hidden=!panel.hidden;sci.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)animate(panel);});exact.addEventListener('click',toggleExact);panel.querySelector('#phase2AngleToggle').addEventListener('click',toggleAngleMode);updateScientificUI();}
  function updateScientificUI(){const button=$('phase2AngleToggle');if(button){button.textContent=`Angle: ${angleMode}`;button.title='Cycle DEG, RAD, GRAD';}}
  function memoryAction(action){let memory=0;try{memory=Number(localStorage.getItem('calculatorMemory')||0);}catch{}try{if(action==='memory-clear')memory=0;else if(action==='memory-recall'){expression=String(memory);justCalculated=true;display(format(memory),'Memory recall');}else{const value=evaluate(expression||'0',{}, {angleMode});if(action==='memory-add')memory+=value;if(action==='memory-subtract')memory-=value;if(action==='memory-store')memory=value;}if(!Number.isFinite(memory))throw new Error('Memory value is not finite');localStorage.setItem('calculatorMemory',String(memory));}catch(error){display('Error',error?.message||'Invalid memory value');}}
  function handleButton(button){const number=button.dataset.number,action=button.dataset.action;if(number!==undefined)return appendNumber(number);if(!action)return;if(action.startsWith('memory-'))return memoryAction(action);if(actionOperators[action])return appendOperator(actionOperators[action]);if(action==='decimal')return appendDecimal();if(action==='equals')return calculate();if(action==='clear'||action==='clear-all')return clear();if(action==='backspace'){if(!justCalculated)expression=expression.slice(0,-1);display(expression||'0');return;}if(action==='open-paren')return appendParenthesis('(');if(action==='close-paren')return appendParenthesis(')');if(scientificActions.includes(action))return scientific(action);}
  function handleKeyboard(event){if(event.ctrlKey||event.metaKey||event.altKey)return;const key=event.key;if(/^[0-9]$/.test(key)){event.preventDefault();event.stopImmediatePropagation();appendNumber(key);return;}if(key==='.') {event.preventDefault();event.stopImmediatePropagation();appendDecimal();return;}if(key==='('||key===')'){event.preventDefault();event.stopImmediatePropagation();appendParenthesis(key);return;}if('+-*/%^'.includes(key)){event.preventDefault();event.stopImmediatePropagation();appendOperator(key);return;}if(key==='Enter'||key==='='){event.preventDefault();event.stopImmediatePropagation();calculate();return;}if(key==='Backspace'){event.preventDefault();event.stopImmediatePropagation();if(!justCalculated)expression=expression.slice(0,-1);display(expression||'0');return;}if(key==='Escape'||key.toLowerCase()==='c'){event.preventDefault();event.stopImmediatePropagation();clear();}}
  document.addEventListener('click',event=>{const button=event.target.closest('.calculator .btn,.calculator .memory-button');if(!button)return;event.preventDefault();event.stopImmediatePropagation();handleButton(button);animate(button);},true);
  document.addEventListener('keydown',handleKeyboard,true);
  window.CalculatorCoreUI=Object.freeze({evaluate,evaluateExact,constants,get angleMode(){return angleMode;},setAngleMode(mode){angleMode=normalizeAngleMode(mode);localStorage.setItem('calculatorAngleMode',angleMode);updateScientificUI();}});
  window.__calculatorCoreUIReady=true;
  createScientificUI();renderHistory();
})();
