class GraphingCalculator {
    constructor() {
        this.panel=document.getElementById('graphPanel');this.canvas=document.getElementById('graphCanvas');this.input=document.getElementById('graphExpression');this.status=document.getElementById('graphStatus');this.ctx=this.canvas?.getContext('2d');this.expression='x^2';this.xMin=-10;this.xMax=10;this.yMin=-10;this.yMax=10;this.dragging=false;this.lastX=0;this.lastY=0;if(!this.panel||!this.canvas||!this.ctx)return;this.bind();this.resize();this.plot();window.addEventListener('resize',()=>this.resize());
    }
    bind(){document.getElementById('graphToggle')?.addEventListener('click',()=>this.toggle());document.getElementById('graphPlot')?.addEventListener('click',()=>this.plotFromInput());document.getElementById('graphReset')?.addEventListener('click',()=>this.reset());document.getElementById('graphZoomIn')?.addEventListener('click',()=>this.zoom(.8));document.getElementById('graphZoomOut')?.addEventListener('click',()=>this.zoom(1.25));this.input?.addEventListener('keydown',e=>{if(e.key==='Enter')this.plotFromInput();});this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY>0?1.15:.87,e.offsetX,e.offsetY);},{passive:false});this.canvas.addEventListener('pointerdown',e=>{this.dragging=true;this.lastX=e.clientX;this.lastY=e.clientY;this.canvas.setPointerCapture(e.pointerId);});this.canvas.addEventListener('pointermove',e=>{if(!this.dragging)return;const dx=e.clientX-this.lastX,dy=e.clientY-this.lastY;this.lastX=e.clientX;this.lastY=e.clientY;const width=Math.max(1,this.canvas.clientWidth),height=Math.max(1,this.canvas.clientHeight);const sx=(this.xMax-this.xMin)/width,sy=(this.yMax-this.yMin)/height;this.xMin-=dx*sx;this.xMax-=dx*sx;this.yMin+=dy*sy;this.yMax+=dy*sy;this.plot();});this.canvas.addEventListener('pointerup',()=>{this.dragging=false;});this.canvas.addEventListener('pointercancel',()=>{this.dragging=false;});this.canvas.addEventListener('pointerleave',()=>{if(this.dragging)this.dragging=false;});}
    toggle(){const open=this.panel.classList.toggle('is-open');this.panel.setAttribute('aria-hidden',String(!open));if(open){requestAnimationFrame(()=>{this.resize();this.plot();});if(typeof anime==='function'&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)anime({targets:this.panel,opacity:[0,1],translateY:[-12,0],duration:420,easing:'easeOutCubic'});}}
    resize(){if(!this.canvas||!this.ctx)return;const rect=this.canvas.getBoundingClientRect(),width=Math.max(1,rect.width),height=Math.max(1,rect.height),dpr=window.devicePixelRatio||1;this.canvas.width=Math.max(1,Math.floor(width*dpr));this.canvas.height=Math.max(1,Math.floor(height*dpr));this.ctx.setTransform(dpr,0,0,dpr,0,0);this.plot();}
    reset(){this.xMin=-10;this.xMax=10;this.yMin=-10;this.yMax=10;if(this.input)this.input.value='x^2';this.plotFromInput();}
    zoom(factor,px,py){const width=Math.max(1,this.canvas.clientWidth),height=Math.max(1,this.canvas.clientHeight);const cx=px==null?width/2:px,cy=py==null?height/2:py,x=this.toX(cx),y=this.toY(cy);this.xMin=x-(x-this.xMin)*factor;this.xMax=x+(this.xMax-x)*factor;this.yMin=y-(y-this.yMin)*factor;this.yMax=y+(this.yMax-y)*factor;this.plot();}
    plotFromInput(){const value=(this.input?.value||'').trim();if(!value)return this.setStatus('Enter an expression such as x^2 or sin(x).',true);try{this.compile(value);this.expression=value;this.setStatus('Plotted: y = '+value,false);this.plot();}catch{this.setStatus('Invalid expression. Try x^2, sin(x), cos(x), tan(x), sqrt(x), or log(x).',true);}}
    compile(source){let expr=source.toLowerCase().replace(/π/g,'pi').replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/\^/g,'**');if(!/^[0-9x+\-*/().,\s_a-z]+$/.test(expr))throw Error('characters');expr=expr.replace(/\bpi\b/g,'Math.PI').replace(/\be\b/g,'Math.E');const names={sin:'Math.sin',cos:'Math.cos',tan:'Math.tan',sqrt:'Math.sqrt',abs:'Math.abs',log:'Math.log10',ln:'Math.log'};Object.entries(names).forEach(([name,fn])=>{expr=expr.replace(new RegExp('\\b'+name+'\\b','g'),fn);});const allowedMath=/Math\.(?:PI|E|sin|cos|tan|sqrt|abs|log10|log)/g;const stripped=expr.replace(allowedMath,'');if(/[A-Za-z_]/.test(stripped)||/[^0-9x+\-*/().,\s]/.test(stripped))throw Error('unsafe');const fn=new Function('x','"use strict";return ('+expr+');');const test=fn(0);if(typeof test!=='number'&&!Number.isNaN(test))throw Error('result');return fn;}
    plot(){if(!this.ctx)return;const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.ctx.clearRect(0,0,w,h);this.drawGrid(w,h);let fn;try{fn=this.compile(this.expression);}catch{return;}this.ctx.save();this.ctx.lineWidth=2;this.ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--graph-line').trim()||getComputedStyle(document.documentElement).getPropertyValue('--text-primary').trim()||'#5ee7ff';this.ctx.beginPath();let started=false,previousY=null;for(let px=0;px<=w;px++){const x=this.toX(px),y=Number(fn(x));if(!Number.isFinite(y)){started=false;previousY=null;continue;}const py=this.toY(y);if(py<-h*3||py>h*3){started=false;previousY=null;continue;}if(!started||previousY!==null&&Math.abs(py-previousY)>h*1.5)this.ctx.moveTo(px,py);else this.ctx.lineTo(px,py);started=true;previousY=py;}this.ctx.stroke();this.ctx.restore();}
    drawGrid(w,h){const s=getComputedStyle(document.documentElement),grid=s.getPropertyValue('--graph-grid').trim()||s.getPropertyValue('--border').trim()||'rgba(128,128,128,.18)',axis=s.getPropertyValue('--graph-axis').trim()||s.getPropertyValue('--border-strong').trim()||'rgba(128,128,128,.65)';this.ctx.lineWidth=1;this.ctx.strokeStyle=grid;this.ctx.fillStyle=s.getPropertyValue('--text-secondary').trim()||'#999';this.ctx.font='10px Inter,sans-serif';const step=this.gridStep();for(let x=Math.ceil(this.xMin/step)*step;x<=this.xMax;x+=step){const px=this.toPx(x,w);this.ctx.beginPath();this.ctx.moveTo(px,0);this.ctx.lineTo(px,h);this.ctx.stroke();if(Math.abs(x)>1e-10)this.ctx.fillText(this.label(x),px+3,Math.min(h-4,Math.max(12,this.toY(0)+12)));}for(let y=Math.ceil(this.yMin/step)*step;y<=this.yMax;y+=step){const py=this.toY(y);this.ctx.beginPath();this.ctx.moveTo(0,py);this.ctx.lineTo(w,py);this.ctx.stroke();if(Math.abs(y)>1e-10)this.ctx.fillText(this.label(y),4,py-3);}this.ctx.strokeStyle=axis;this.ctx.lineWidth=1.5;const ax=this.toPx(0,w),ay=this.toY(0);if(ax>=0&&ax<=w){this.ctx.beginPath();this.ctx.moveTo(ax,0);this.ctx.lineTo(ax,h);this.ctx.stroke();}if(ay>=0&&ay<=h){this.ctx.beginPath();this.ctx.moveTo(0,ay);this.ctx.lineTo(w,ay);this.ctx.stroke();}}
    gridStep(){const raw=Math.max(this.xMax-this.xMin,this.yMax-this.yMin)/10,p=Math.pow(10,Math.floor(Math.log10(raw))),n=raw/p;return(n<2?1:n<5?2:5)*p;}
    toX(px){return this.xMin+(px/Math.max(1,this.canvas.clientWidth))*(this.xMax-this.xMin)}toY(y){return Math.max(1,this.canvas.clientHeight)-((y-this.yMin)/(this.yMax-this.yMin))*Math.max(1,this.canvas.clientHeight)}toPx(x,w){return((x-this.xMin)/(this.xMax-this.xMin))*w}label(v){return Math.abs(v)>=1000?v.toExponential(0):String(Number(v.toFixed(4)));}setStatus(t,error){if(this.status){this.status.textContent=t;this.status.classList.toggle('error',error);}}
}
document.addEventListener('DOMContentLoaded',()=>new GraphingCalculator());
