class Calculator {
    constructor() {
        this.primary=document.getElementById('displayPrimary');this.secondary=document.getElementById('displaySecondary');this.scientificToggle=document.getElementById('scientificToggle');this.scientificPanel=document.getElementById('scientificPanel');this.historyToggle=document.getElementById('historyToggle');this.historyPanel=document.getElementById('historyPanel');this.historyList=document.getElementById('historyList');this.historyCount=document.getElementById('historyCount');this.clearHistoryButton=document.getElementById('clearHistory');this.memoryDisplay=document.getElementById('memoryValue');this.themeToggle=document.getElementById('themeToggle');
        this.current='0';this.previous=null;this.operator=null;this.waiting=false;this.justCalculated=false;this.errorTimer=null;this.history=this.readHistory();this.memory=this.readMemory();this.theme=this.readTheme();this.applyTheme(false);this.bindEvents();this.renderHistory();this.renderMemory();this.render(false);this.animateEntrance();
    }
    bindEvents(){document.querySelectorAll('.btn,.memory-button').forEach(button=>button.addEventListener('click',()=>{this.handleAction(button.dataset.action,button.dataset.number);this.animateButton(button);}));this.scientificToggle.addEventListener('click',()=>this.toggleScientific());this.historyToggle.addEventListener('click',()=>this.toggleHistory());this.clearHistoryButton.addEventListener('click',()=>this.clearHistory());this.themeToggle.addEventListener('click',()=>this.toggleTheme());document.addEventListener('keydown',event=>this.keyboard(event));}
    readTheme(){try{const value=localStorage.getItem('calculatorTheme');return['dark','light','system'].includes(value)?value:'dark';}catch(_){return'dark';}}
    saveTheme(){try{localStorage.setItem('calculatorTheme',this.theme);}catch(_){} }
    applyTheme(animate=true){document.documentElement.dataset.theme=this.theme;const icon=this.theme==='light'?'fa-sun':this.theme==='system'?'fa-circle-half-stroke':'fa-moon';this.themeToggle.innerHTML=`<i class="fas ${icon}"></i>`;this.themeToggle.setAttribute('aria-label',`Theme: ${this.theme}. Click to change`);if(animate)this.animateThemeChange();}
    toggleTheme(){this.theme=this.theme==='dark'?'light':this.theme==='light'?'system':'dark';this.saveTheme();this.applyTheme();}
    readHistory(){try{const value=JSON.parse(localStorage.getItem('calculatorHistory')||'[]');return Array.isArray(value)?value.slice(0,50):[];}catch(_){return[];}}
    saveHistory(){try{localStorage.setItem('calculatorHistory',JSON.stringify(this.history));}catch(_){} }
    readMemory(){try{const value=Number(localStorage.getItem('calculatorMemory')||0);return Number.isFinite(value)?value:0;}catch(_){return 0;}}
    saveMemory(){try{localStorage.setItem('calculatorMemory',String(this.memory));}catch(_){} }
    renderMemory(){this.memoryDisplay.textContent=this.format(this.memory);}
    memoryAction(action){this.cancelError();const value=Number(this.current);if(action==='memory-clear')this.memory=0;else if(action==='memory-recall'){this.current=String(this.memory);this.waiting=false;this.justCalculated=true;this.secondary.textContent='Memory recall';}else if(action==='memory-add'){if(!Number.isFinite(value))return this.showError('Invalid number');this.memory=this.round(this.memory+value);}else if(action==='memory-subtract'){if(!Number.isFinite(value))return this.showError('Invalid number');this.memory=this.round(this.memory-value);}else if(action==='memory-store'){if(!Number.isFinite(value))return this.showError('Invalid number');this.memory=this.round(value);}else return;this.saveMemory();this.renderMemory();this.render();this.animateMemoryAction(action);}
    handleAction(action,number){if(number!==undefined)return this.inputNumber(number);if(!action)return;if(action.startsWith('memory-'))return this.memoryAction(action);if(action==='decimal')return this.decimal();if(action==='equals')return this.calculate();if(action==='clear')return this.clearCurrent();if(action==='clear-all')return this.clearAll();if(action==='backspace')return this.backspace();if(['add','subtract','multiply','divide'].includes(action))return this.setOperator(action);if(['sin','cos','tan','log','ln','sqrt','square','reciprocal','percent','factorial'].includes(action))return this.scientific(action);if(action==='pi')return this.constant(Math.PI,'π');if(action==='e')return this.constant(Math.E,'e');}
    inputNumber(number){this.cancelError();if(this.waiting||this.justCalculated){this.current=number;this.waiting=false;this.justCalculated=false;if(!this.operator)this.secondary.textContent='';}else this.current=this.current==='0'?number:this.current+number;this.render();}
    decimal(){this.cancelError();if(this.waiting||this.justCalculated){this.current='0.';this.waiting=false;this.justCalculated=false;this.secondary.textContent='';}else if(!this.current.includes('.'))this.current+='.';this.render();}
    setOperator(next){this.cancelError();const value=Number(this.current);if(!Number.isFinite(value))return this.showError('Invalid number');if(this.previous===null)this.previous=value;else if(this.operator&&!this.waiting){const result=this.compute();if(result===null)return;this.current=String(result);this.previous=result;}this.operator=next;this.waiting=true;this.justCalculated=false;this.updateSecondary();this.render();}
    compute(){const a=Number(this.previous),b=Number(this.current);if(!Number.isFinite(a)||!Number.isFinite(b))return null;if(this.operator==='add')return this.round(a+b);if(this.operator==='subtract')return this.round(a-b);if(this.operator==='multiply')return this.round(a*b);if(this.operator==='divide'){if(b===0){this.showError('Cannot divide by zero');return null;}return this.round(a/b);}return null;}
    calculate(){this.cancelError();if(this.previous===null||!this.operator||this.waiting)return;const left=this.format(this.previous),right=this.format(this.current),symbol=this.symbol(this.operator),result=this.compute();if(result===null)return;this.addHistory(`${left} ${symbol} ${right}`,result);this.secondary.textContent=`${left} ${symbol} ${right} =`;this.current=String(result);this.previous=null;this.operator=null;this.waiting=false;this.justCalculated=true;this.render();this.animateResult();}
    scientific(type){this.cancelError();const value=Number(this.current);if(!Number.isFinite(value))return this.showError('Invalid number');let result;if(type==='sin')result=Math.sin(value*Math.PI/180);else if(type==='cos')result=Math.cos(value*Math.PI/180);else if(type==='tan'){const radians=value*Math.PI/180;if(Math.abs(Math.cos(radians))<1e-12)return this.showError('Undefined tan');result=Math.tan(radians);}else if(type==='log'){if(value<=0)return this.showError('log requires > 0');result=Math.log10(value);}else if(type==='ln'){if(value<=0)return this.showError('ln requires > 0');result=Math.log(value);}else if(type==='sqrt'){if(value<0)return this.showError('√ requires ≥ 0');result=Math.sqrt(value);}else if(type==='square')result=value*value;else if(type==='reciprocal'){if(value===0)return this.showError('Cannot divide by zero');result=1/value;}else if(type==='percent')result=value/100;else if(type==='factorial'){if(!Number.isInteger(value)||value<0||value>170)return this.showError('Use an integer 0–170');result=1;for(let i=2;i<=value;i++)result*=i;}this.current=String(this.round(result));this.justCalculated=true;this.waiting=false;this.secondary.textContent=`${type}(${this.format(value)})`;this.render();this.animateResult();}
    constant(value,name){this.cancelError();this.current=String(this.round(value));this.justCalculated=true;this.waiting=false;this.secondary.textContent=name;this.render();this.animateResult();}
    clearCurrent(){this.cancelError();this.current='0';this.render();}clearAll(){this.cancelError();this.current='0';this.previous=null;this.operator=null;this.waiting=false;this.justCalculated=false;this.secondary.textContent='';this.render();}backspace(){this.cancelError();if(this.waiting||this.justCalculated)return;this.current=this.current.length>1?this.current.slice(0,-1):'0';if(this.current==='-')this.current='0';this.render();}
    updateSecondary(){if(this.previous!==null&&this.operator)this.secondary.textContent=`${this.format(this.previous)} ${this.symbol(this.operator)}`;}symbol(operator){return{add:'+',subtract:'−',multiply:'×',divide:'÷'}[operator]||'';}
    render(animate=true){this.primary.textContent=this.format(this.current);this.primary.classList.remove('display-error');if(animate)this.animateDisplay();}format(value){const number=Number(value);if(!Number.isFinite(number))return'Error';if(Math.abs(number)>=1e10||(Math.abs(number)<1e-6&&number!==0))return number.toExponential(6);return number.toLocaleString('en-US',{maximumFractionDigits:8,useGrouping:false});}round(value){return Number.isFinite(value)?Math.round((value+Number.EPSILON)*1e8)/1e8:value;}
    addHistory(expression,result){this.history.unshift({expression,result:String(result),time:Date.now()});this.history=this.history.slice(0,50);this.saveHistory();this.renderHistory();this.animateHistoryItem();}renderHistory(){this.historyCount.textContent=String(this.history.length);if(!this.history.length){this.historyList.innerHTML='<div class="history-empty">No calculations yet</div>';return;}this.historyList.innerHTML='';this.history.forEach(entry=>{const button=document.createElement('button');button.type='button';button.className='history-item';button.innerHTML='<span class="history-expression"></span><span class="history-result"></span>';button.querySelector('.history-expression').textContent=entry.expression;button.querySelector('.history-result').textContent='= '+this.format(entry.result);button.addEventListener('click',()=>{this.current=entry.result;this.previous=null;this.operator=null;this.waiting=false;this.justCalculated=true;this.secondary.textContent='';this.render();this.toggleHistory(false);this.animateResult();});this.historyList.appendChild(button);});}clearHistory(){this.history=[];this.saveHistory();this.renderHistory();}
    toggleHistory(force){const open=typeof force==='boolean'?force:!this.historyPanel.classList.contains('is-open');this.historyPanel.classList.toggle('is-open',open);this.historyPanel.setAttribute('aria-hidden',String(!open));this.historyToggle.setAttribute('aria-expanded',String(open));if(open)this.animateHistoryPanel();}toggleScientific(){const open=this.scientificPanel.classList.toggle('is-open');this.scientificPanel.setAttribute('aria-hidden',String(!open));this.scientificToggle.setAttribute('aria-expanded',String(open));this.scientificToggle.innerHTML=open?'<i class="fas fa-flask"></i> Hide Scientific Mode':'<i class="fas fa-flask"></i> Scientific Mode';if(open)this.animateScientificPanel();}
    keyboard(event){const key=event.key;if(/^[0-9]$/.test(key)){event.preventDefault();this.inputNumber(key);return;}const actions={'+':'add','-':'subtract','*':'multiply','/':'divide','.':'decimal','=':'equals',Enter:'equals',Escape:'clear-all',Backspace:'backspace',c:'clear',C:'clear'};if(actions[key]){event.preventDefault();this.handleAction(actions[key]);}}
    showError(message){this.cancelError();this.primary.textContent='Error';this.primary.classList.add('display-error');this.secondary.textContent=message;this.errorTimer=setTimeout(()=>{this.errorTimer=null;this.clearAll();},2000);}cancelError(){if(this.errorTimer!==null){clearTimeout(this.errorTimer);this.errorTimer=null;}}
    animateEntrance(){if(typeof anime!=='function')return;anime.timeline({easing:'easeOutExpo'}).add({targets:'.calculator-header',opacity:[0,1],translateY:[-30,0],duration:650}).add({targets:'.calculator',opacity:[0,1],scale:[.96,1],translateY:[24,0],duration:700,offset:'-=450'}).add({targets:'.calculator-footer',opacity:[0,1],translateY:[12,0],duration:400,offset:'-=400'}).add({targets:'.button-grid .btn',opacity:[0,1],translateY:[18,0],scale:[.88,1],duration:520,delay:anime.stagger(35,{grid:[4,5],from:'center'}),easing:'easeOutBack',offset:'-=260'});}
    animateButton(button){if(typeof anime!=='function')return;anime.remove(button);anime({targets:button,scale:[.94,1.08,1],duration:360,easing:'easeOutElastic(1,.55)'});}animateDisplay(){if(typeof anime!=='function')return;anime.remove(this.primary);anime({targets:this.primary,scale:[1,.985,1.015,1],duration:260,easing:'easeOutCubic'});}animateResult(){if(typeof anime!=='function')return;anime.remove(this.primary);anime({targets:this.primary,opacity:[.2,1],scale:[.82,1.08,1],translateY:[8,0],duration:600,easing:'easeOutElastic(1,.5)'});}
    animateMemoryAction(action){if(typeof anime!=='function')return;anime({targets:'.memory-panel',scale:[1,.985,1.02,1],duration:420,easing:'easeOutElastic(1,.6)'});if(action==='memory-recall')this.animateResult();}animateHistoryPanel(){if(typeof anime!=='function')return;anime.remove('.history-item,.history-empty');anime({targets:'.history-item,.history-empty',opacity:[0,1],translateX:[-18,0],scale:[.96,1],duration:420,delay:anime.stagger(45),easing:'easeOutCubic'});}animateHistoryItem(){if(typeof anime!=='function')return;anime({targets:'.history-item:first-child',opacity:[0,1],translateX:[-20,0],scale:[.94,1],duration:500,easing:'easeOutBack'});}animateScientificPanel(){if(typeof anime!=='function')return;anime.remove('.scientific-panel .btn');anime({targets:'.scientific-panel .btn',opacity:[0,1],translateY:[-14,0],scale:[.82,1],duration:500,delay:anime.stagger(45,{grid:[4,3],from:'center'}),easing:'easeOutBack'});}animateThemeChange(){if(typeof anime!=='function')return;anime.remove('.calculator,.display-container,.memory-panel,.theme-toggle');anime({targets:'.calculator',scale:[.985,1],duration:450,easing:'easeOutCubic'});anime({targets:'.display-container,.memory-panel',opacity:[.75,1],translateY:[4,0],duration:400,easing:'easeOutCubic'});anime({targets:'.theme-toggle',rotate:[0,360],scale:[.85,1],duration:550,easing:'easeOutBack'});}
}
document.addEventListener('DOMContentLoaded',()=>new Calculator());
