(() => {
  const init = () => {
    const sidebar=document.getElementById('featureSidebar'),openBtn=document.getElementById('sidebarOpen'),closeBtn=document.getElementById('sidebarClose'),backdrop=document.getElementById('sidebarBackdrop'),calculator=document.querySelector('.calculator');
    if(!sidebar||!openBtn||!closeBtn||!calculator)return;
    const list=sidebar.querySelector('.feature-list');if(!list)return;
    // Replace controls once to detach legacy listeners without cloning the sidebar itself.
    const fresh=n=>n?.parentNode?.replaceChild(n.cloneNode(true),n);
    fresh(openBtn);fresh(closeBtn);if(backdrop)fresh(backdrop);
    const open=document.getElementById('sidebarOpen'),close=document.getElementById('sidebarClose'),shade=document.getElementById('sidebarBackdrop');
    const featureNodes={history:[calculator.querySelector('.calculator-tools'),document.getElementById('historyPanel')],memory:[calculator.querySelector('.memory-panel')],scientific:[document.getElementById('scientificPanel')],graph:[document.getElementById('graphPanel')],statistics:[document.getElementById('statisticsPanel')]};
    const allNodes=[...new Set(Object.values(featureNodes).flat().filter(Boolean))];
    const buttonGrid=calculator.querySelector('.button-grid');allNodes.forEach(node=>{if(node.parentElement!==calculator)calculator.insertBefore(node,buttonGrid);});
    const style=document.getElementById('sidebar-main-layout-style')||document.createElement('style');style.id='sidebar-main-layout-style';style.textContent=`.calculator .sidebar-feature-hidden{display:none!important}.calculator .sidebar-feature-visible{display:block!important}.calculator .sidebar-feature-visible.calculator-tools,.calculator .sidebar-feature-visible.scientific-panel{display:grid!important}.feature-sidebar{background:var(--bg-secondary);color:var(--text-primary);border-color:var(--border)}.feature-sidebar .feature-item{background:var(--surface);color:var(--text-primary);border:1px solid var(--border);transition:transform .16s ease,background .16s ease,border-color .16s ease}.feature-sidebar .feature-item:hover,.feature-sidebar .feature-item.active{background:var(--surface-2);border-color:var(--border-strong);transform:translateX(2px)}.feature-sidebar .feature-item:active{transform:scale(.98)}.feature-sidebar .feature-item i{color:var(--text-secondary)}.feature-sidebar .feature-list{gap:8px}.feature-sidebar .feature-item[data-feature="theme"]{margin-top:6px}`;if(!style.parentNode)document.head.appendChild(style);
    const reduced=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const animate=(targets,props)=>{if(typeof anime!=='function'||reduced())return;anime.remove(targets);anime({targets,...props});};
    const setState=(isOpen)=>{sidebar.classList.toggle('is-open',isOpen);shade?.classList.toggle('is-open',isOpen);sidebar.setAttribute('aria-hidden',String(!isOpen));open.setAttribute('aria-expanded',String(isOpen));};
    const closeSidebar=()=>{if(typeof anime==='function'&&!reduced()){anime.remove(sidebar);anime({targets:sidebar,translateX:['0%','-105%'],duration:190,easing:'easeInCubic',complete:()=>sidebar.style.removeProperty('transform')});}setState(false);};
    const openSidebar=()=>{setState(true);sidebar.style.transform='translateX(-105%)';animate(sidebar,{translateX:['-105%','0%'],duration:240,easing:'easeOutCubic',complete:()=>sidebar.style.removeProperty('transform')});};
    const reset=()=>{allNodes.forEach(n=>{n.classList.remove('sidebar-feature-visible','sidebar-feature-hidden','is-open');n.setAttribute('aria-hidden','true');});['historyToggle','scientificToggle','graphToggle','statisticsToggle'].forEach(id=>document.getElementById(id)?.setAttribute('aria-expanded','false'));};
    const activate=feature=>{list.querySelectorAll('.feature-item').forEach(i=>i.classList.toggle('active',i.dataset.feature===feature));reset();if(feature==='theme'){document.getElementById('themeToggle')?.click();closeSidebar();return;}if(feature==='basic'){closeSidebar();return;}const nodes=(featureNodes[feature]||[]).filter(Boolean);if(!nodes.length)return;nodes.forEach(n=>{n.classList.add('sidebar-feature-visible','is-open');n.setAttribute('aria-hidden','false');});if(feature==='history')document.getElementById('historyToggle')?.setAttribute('aria-expanded','true');closeSidebar();requestAnimationFrame(()=>{if(feature==='graph'){window.dispatchEvent(new Event('resize'));}animate(nodes,{opacity:[0,1],translateY:[8,0],duration:220,delay:typeof anime==='function'?anime.stagger(20):0,easing:'easeOutCubic'});});};
    open.addEventListener('click',e=>{e.preventDefault();openSidebar();});close.addEventListener('click',e=>{e.preventDefault();closeSidebar();});shade?.addEventListener('click',closeSidebar);list.addEventListener('click',e=>{const item=e.target.closest('.feature-item');if(!item||!list.contains(item))return;e.preventDefault();e.stopPropagation();activate(item.dataset.feature);});
    const keyHandler=e=>{if(e.key==='Escape'&&sidebar.classList.contains('is-open'))closeSidebar();};document.addEventListener('keydown',keyHandler);reset();setState(false);sidebar.style.removeProperty('transform');
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
